version: "3.9"

services:
  chat_room:
    container_name: chat_room
    build: ./chat_room
    ports:
      - 8888:8888
    volumes:
      - ./chat_room:/app
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume: